name: build dotnet application

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    
jobs:
  build:   
  runs-on: windows-latest


  steps:              
    - name: checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: build
      run: |
        dotnet restore
        dotnet build --configuration Release
      shell: powershell
